import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ProductsService {
  public products = [
    // Smart Direct
    {
      account_type: 'PURE_SAVE',
      code: '70',
      name: 'smart-direct',
      policy_image: 'assets/images/smart_direct.png',
      policy_title: 'Smart Direct',
      policy_description: `Smart Living starts with Smart Direct Account.
      Get Income Protection and Life Insurance for just Kes 100 per month.`,
      monthly_fees: 'Ksh. 100',
      opening_balance: 'Nill',
      target_market: [
        'Preferable for salaried individuals earning between Kes 15,000 and Kes 150,000',
        'Must be a Kenyan Citizen',
        'Must be 18 years and above in age',
      ],
      benefits: [
        'Income protection i.e. retrenchment cover of up to Kes 450,000*. This is available to salaried clients',
        'Life cover of 6 months gross income/salary capped at Kes 900,000*  ',
        'Funeral Cover of Kes 100,000*',
        'Ability to make payments locally and internationally via our digital channels',
        'Access to Silver debit and credit card with no joining fees',
        'Access to monthly cash advance via mobile banking',
        'Free salary credit',
        'Free internet Banking access from anywhere in the world',
        'Free e statements ',
        'Terms and conditions apply',
      ],
      features: [
        'A monthly ledger fee of only Kes 100 per month',
        'Access to multiple current accounts in different currencies for the bundle fee',
        'Available to both salaried and non-salaried individuals ',
        'No minimum operating balance ',
        'Ability to deposit funds via MPESA',
        'Pay as you transact for all transactions with an instant ledger fee of Kes 40 for non-self-service transactions i.e. transactions done at the branch',
      ],
    },
    // Executive Banking
    {
      account_type: 'PURE_SAVE',
      code: '100',
      name: 'gold-bundle',
      policy_image: 'assets/images/executive_banking.png',
      policy_title: 'Executive Banking',
      policy_description: `Would you like to accelerate your hopes & aspiration on financial independence?
      Our solutions are tailormade to make them a reality. For just Kes 990 per month,
      you get a dedicated Executive banker with a wealth of knowledge and experience to offer you personalised banking.  `,
      monthly_fees: 'No Fees',
      opening_balance: 'Ksh. 10000',
      target_market: [
        'Preferable for salaried individuals earning between Kes 150,000 and Kes 450,000 ',
        'Must be a Kenyan Citizen ',
        'Must be 18 years and above in age',
      ],
      benefits: [
        `Income protection i.e. retrenchment cover of up to Kes 900,000*. This is equivalent to a gross salary of Kes 
      300,000 per month and is available to salaried clients only`,
        'Life cover of 6 months gross income/salary capped at Kes 1.8M* ',
        'Funeral Cover of Kes 100,000*',
        'Access to an executive banker and a team of executive assistants to cater to your financial needs ',
        'No minimum operating balance',
        'Ability to make payments locally and internationally via our digital channels',
        'Dedicated tellers in select branches ',
        'Access to loans',
        'Personalised Banking',
        '*Terms and conditions apply ',
      ],
      features: [
        'A bundle fee of Kes 990 per month',
        'Access to multiple current account in different currencies for the bundle fee',
        'Available to both salaried and non-salaried individuals',
        '4 free cash withdrawals per month',
        '2 free Bankers Cheques per month',
        '1 free External Standing Order per month ',
        'Free Stanbic Bank ATM Cash Withdrawals ',
        'Ability to deposit funds via MPESA ',
        'Access to gold debit and credit card with no joining fees ',
        'Access to monthly cash advance via mobile banking',
        'Free salary credit',
      ],
    },
    // PAYG
    {
      account_type: 'PURE_SAVE',
      code: '60',
      name: 'payg',
      policy_image: 'assets/images/pay_as_you_go.png',
      policy_title: 'Pay As You Go',
      policy_description: `Enjoy transactional banking which will enable you to make payments by cheques,
      bank transfers, debit card payments, drafts or online transfers and only pay when you transact.`,
      monthly_fees: 'Ksh. 100',
      opening_balance: 'Nill',
      target_market: [
        'Preferable for all individuals who want a pay as you transact account with no monthly charges',
        'Must be a Kenyan citizen',
        'Must be 18 years and above',
      ],
      benefits: [
        'Free monthly e-statements upon signing up',
        'Free Internet Banking access from anywhere in the world',
        'Ability to make internal and interbank payment via Internet Banking',
        'Mobile banking linked to your account',
        'Ability to deposit funds via M-PESA',
        'Access to cheque book',
        'Access to loans',
        'No minimum operating balance',
      ],
      features: [
        'Minimum opening balance of Kes. 1,000',
        'No monthly ledger fees charged.',
        'No minimum operating balance',
        'Access to monthly cash advance',
        'Can be opened for both local and foreign currencies',
      ],
    },
    // Pamoja Trader\ Business Account
    {
      account_type: 'BUSINESS_PAMOJA',
      code: '150',
      name: 'pamoja',
      policy_image: 'assets/images/pamoja_trader.png',
      policy_title: 'Pamoja Trader/Business Account',
      policy_description: `This solution emphasizes our aspirations in working together with you (Pamoja) to provide superior service
      in line with your needs at an affordable price. This account is ideal
      for micro-enterprises where you will only pay for the services utilised.`,
      monthly_fees: 'Ksh. 100',
      opening_balance: '15,000',
      target_market: [
        'Preferable for people in business trading as themselves ',
        'Must be a Kenyan citizen',
        'Must be 18 years and above',
      ],
      benefits: [
        'Access to loans',
        'Free monthly e-statements upon signing up ',
        'Free Internet Banking access from anywhere in the world',
        'Ability to make internal and interbank payment via Internet Banking ',
        'Mobile banking linked to your account ',
        'Ability to deposit funds via M-PESA',
        'Access to MPESA Tills linked to your account with real time settlement',
        'Access to cheque book',
        'No minimum operating balance',
      ],
      features: [
        'Minimum opening balance of Kes. 1,000 ',
        'No monthly ledger fees charged.',
        'No minimum operating balance',
        'Access to monthly cash advance',
        'Can be opened for both local and foreign currencies',
      ],
    },
    // Private Banking
    {
      account_type: 'PURE_SAVE',
      code: '130',
      name: 'pvt',
      policy_image: 'assets/images/private_banking.png',
      policy_title: 'Private Banking',
      policy_description: `Through a dedicated team of Private bankers, we provide a
      personalised service and tailormade Bespoke Solutions to suite your Individually unique requirements. Relationships are important to us. That is why we offer you one point of contact to our network of professionals, regardless of whether you are travelling or visiting your local branch. For a monthly fee of Kes. 2,000 we have enclosed a range of products and services at your disposal to better meet your needs`,
      monthly_fees: 'Ksh. 100',
      opening_balance: '15,000',
      target_market: [
        'Preferably for individuals and professionals with an Income of Kes 450,000 and above',
        'Must be a Kenyan Citizen of age 18 years and above ',
      ],
      benefits: [
        'Dedicated Private Banker 24/7 to assist you with your financial needs ',
        'Banking suites and single point of contact with the bank ',
        'Access to offshore banking with Standard Bank Isle of Man ',
        'Free personal accident insurance (Kes 1,000,000)* ',
        'Automatic overdraft line on joining Private Banking ',
        'Preferential FX rates ',
        'Quarterly newsletter and global markets information ',
        'Preferential lending rates ',
        'Access to home loans, vehicle asset finance and unsecured loans of up to Kes 4M* ',
        'Investment Advice',
        'Wealth Management',
        '*Terms and conditions apply ',
      ],
      features: [
        'A bundle fee of Kes 2,000 per month ',
        'Access to multiple current account in different currencies for the bundle fee ',
        'No minimum operating and operating balance ',
        'Free e-statements, Stanbic ATM Cash Withdrawals, internet banking access and salary credits',
        'Unlimited free cheque books, banker’s cheque, over the counter cash withdrawals ',
        'Free internal standing orders ',
        'Access to a platinum Mastercard Credit Card with no joining fee ',
        'Free Platinum debit card including secondary card if requested',
        'Mobile Banking linked to your account',
      ],
    },
    // Diaspora Banking
    {
      account_type: 'PURE_SAVE',
      code: '160',
      name: 'diaspora',
      policy_image: 'assets/images/diaspora_banking.png',
      policy_title: 'Diaspora Banking',
      policy_description: `Invest & bank as if you were home. Enjoy transactional banking which will enable you to make payments and only pay when you transact.`,
      monthly_fees: 'Ksh. 100',
      opening_balance: '15,000',
      target_market: [
        'All Kenyans Citizens living in the Diaspora',
        'Must be age 18 year and above ',
      ],
      benefits: [
        'Dedicated team',
        'Preferential rates on your deposits',
        'Preferential forex rates',
        'Access to personal/family medical insurance',
        'Free monthly e-statements upon signing up',
        'Free Internet Banking access from anywhere in the world',
        'Ability to make internal and interbank payment via Internet Banking',
        'Mobile banking linked to your account',
        'Ability to send MPESA from internet & mobile banking',
        'Ability to deposit funds via M-PESA',
        'Access to our mortgage financing team',
      ],
      features: [
        'Available in local and foreign currency i.e. KES, USD, GBP and EUR with primary account KES ',
        'Ability to open savings and fixed deposits from internet banking',
        'No minimum operating balance',
        'Access to our 24-hour customer care centre',
      ],
    },
    // Joint Account
    {
      account_type: 'JOINT',
      code: '160',
      name: 'diaspora',
      policy_image: 'assets/images/diaspora_banking.png',
      policy_title: 'Joint Account',
      policy_description: `Invest & bank as if you were home. Enjoy transactional banking which will enable you to make payments and only pay when you transact.`,
      monthly_fees: 'Ksh. 100',
      opening_balance: '15,000',
      target_market: [
        'All Kenyans Citizens living in the Diaspora',
        'Must be age 18 year and above ',
      ],
      benefits: [
        'Dedicated team',
        'Preferential rates on your deposits',
        'Preferential forex rates',
        'Access to personal/family medical insurance',
        'Free monthly e-statements upon signing up',
        'Free Internet Banking access from anywhere in the world',
        'Ability to make internal and interbank payment via Internet Banking',
        'Mobile banking linked to your account',
        'Ability to send MPESA from internet & mobile banking',
        'Ability to deposit funds via M-PESA',
        'Access to our mortgage financing team',
      ],
      features: [
        'Available in local and foreign currency i.e. KES, USD, GBP and EUR with primary account KES ',
        'Ability to open savings and fixed deposits from internet banking',
        'No minimum operating balance',
        'Access to our 24-hour customer care centre',
      ],
    },
    // Child Account
    {
      account_type: 'CHILD',
      code: '160',
      name: 'diaspora',
      policy_image: 'assets/images/diaspora_banking.png',
      policy_title: 'Child Account',
      policy_description: `Invest & bank as if you were home. Enjoy transactional banking which will enable you to make payments and only pay when you transact.`,
      monthly_fees: 'Ksh. 100',
      opening_balance: '15,000',
      target_market: [
        'All Kenyans Citizens living in the Diaspora',
        'Must be age 18 year and above ',
      ],
      benefits: [
        'Dedicated team',
        'Preferential rates on your deposits',
        'Preferential forex rates',
        'Access to personal/family medical insurance',
        'Free monthly e-statements upon signing up',
        'Free Internet Banking access from anywhere in the world',
        'Ability to make internal and interbank payment via Internet Banking',
        'Mobile banking linked to your account',
        'Ability to send MPESA from internet & mobile banking',
        'Ability to deposit funds via M-PESA',
        'Access to our mortgage financing team',
      ],
      features: [
        'Available in local and foreign currency i.e. KES, USD, GBP and EUR with primary account KES ',
        'Ability to open savings and fixed deposits from internet banking',
        'No minimum operating balance',
        'Access to our 24-hour customer care centre',
      ],
    },
  ];

  constructor() {}
}
